version: "3.8"

services:
  web:
    image: ${DOCKER_IMAGE}
    container_name: ${PROJECT_NAME}-web
    restart: always
    env_file:
      - ../envs/.env-${GITHUB_REPOSITORY_NAME}
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.${HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=myresolver"
    depends_on:
      - db

  db:
    image: mariadb
    container_name: ${PROJECT_NAME}-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - web

networks:
  web:
    external: true

volumes:
  db-data:
