name: CD-traefik

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🛠️ Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ vars.PROJECT_NAME }}:latest

      - name: 🚀 Deploy on VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ vars.PROJECT_NAME }}:latest

            docker stop ${{ vars.PROJECT_NAME }}-web || true
            docker rm ${{ vars.PROJECT_NAME }}-web || true

            docker network ls | grep -q proxy || docker network create proxy

            # Load main infra env vars
            GLOBAL_ENV_PATH=/home/ubuntu/traefik/data/.env
            HOST=$(grep '^HOST=' $GLOBAL_ENV_PATH | cut -d '=' -f2)
            APP_SECRET=$(grep '^APP_SECRET=' $GLOBAL_ENV_PATH | cut -d '=' -f2)
            DB_HOST="$(grep '^DATABASE_SUBDOMAIN_NAME=' $GLOBAL_ENV_PATH | cut -d '=' -f2)-db"
            DB_USER=$(grep '^USER_NAME=' $GLOBAL_ENV_PATH | cut -d '=' -f2)
            DB_PASSWORD=$(grep '^USER_PASSWORD=' $GLOBAL_ENV_PATH | cut -d '=' -f2)

            # Create project-specific .env
            ENV_PROJECT_PATH=/tmp/${{ vars.PROJECT_NAME }}.env

            cat <<EOF > $ENV_PROJECT_PATH
            APP_PORT=3310
            APP_SECRET=$APP_SECRET
            DB_HOST=$DB_HOST
            DB_PORT=3306
            DB_USER=$DB_USER
            DB_PASSWORD=$DB_PASSWORD
            DB_NAME=${{ vars.PROJECT_NAME }}
            HOST=$HOST
            DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ vars.PROJECT_NAME }}:latest
            PROJECT_NAME=${{ vars.PROJECT_NAME }}
            EOF

            echo "✅ .env projet généré avec succès ✅"
            grep -E '^(APP_PORT|DB_HOST|DB_NAME|HOST)=' $ENV_PROJECT_PATH

            cd /home/ubuntu/projects/${{ vars.PROJECT_DIRECTORY_NAME }}

            # Inject vars as shell env for strict docker-compose parsing
            set -a
            source $ENV_PROJECT_PATH
            set +a

            COMPOSE_FILE=docker-compose.prod.yml \
            COMPOSE_PROJECT_NAME=${{ vars.PROJECT_NAME }} \
            docker compose --env-file $ENV_PROJECT_PATH up -d --remove-orphans --force-recreate

            echo "⏳ Attente du démarrage du container..."
            sleep 10

            echo "🚀 Lancement de la migration..."
            docker exec ${{ vars.PROJECT_NAME }}-web npm run migrate || echo "❗ Migration échouée ou non nécessaire"
